# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI\settings_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 400)
        Dialog.setStyleSheet("QPushButton{\n"
"height: 36px;\n"
"border: 1px solid;\n"
"border-radius: 4px;\n"
"border-color:  rgba(0, 0, 0, 0.12);\n"
"color: #6200ee;\n"
"font: \"Roboto\";\n"
"font-size: 20px;\n"
"padding: 5px\n"
"}\n"
"QPushButton::hover{\n"
"    background-color: rgb(230, 230, 230);\n"
"}\n"
"QPushButton::pressed{\n"
"    background-color: rgb(179, 179, 179);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chrome_version_label = QtWidgets.QLabel(Dialog)
        self.chrome_version_label.setObjectName("chrome_version_label")
        self.verticalLayout.addWidget(self.chrome_version_label)
        self.chrome_version_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.chrome_version_lineEdit.setObjectName("chrome_version_lineEdit")
        self.verticalLayout.addWidget(self.chrome_version_lineEdit)
        self.checkBox_autoreg = QtWidgets.QCheckBox(Dialog)
        self.checkBox_autoreg.setObjectName("checkBox_autoreg")
        self.verticalLayout.addWidget(self.checkBox_autoreg)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Ukraine))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 346, 67))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEditAddPage = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditAddPage.sizePolicy().hasHeightForWidth())
        self.lineEditAddPage.setSizePolicy(sizePolicy)
        self.lineEditAddPage.setObjectName("lineEditAddPage")
        self.horizontalLayout_2.addWidget(self.lineEditAddPage)
        self.pushButton_remove_page = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_remove_page.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_remove_page.sizePolicy().hasHeightForWidth())
        self.pushButton_remove_page.setSizePolicy(sizePolicy)
        self.pushButton_remove_page.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_remove_page.setObjectName("pushButton_remove_page")
        self.horizontalLayout_2.addWidget(self.pushButton_remove_page)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.addWidget(self.scrollArea)
        self.pushButton_add_page = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_add_page.sizePolicy().hasHeightForWidth())
        self.pushButton_add_page.setSizePolicy(sizePolicy)
        self.pushButton_add_page.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_add_page.setObjectName("pushButton_add_page")
        self.horizontalLayout_3.addWidget(self.pushButton_add_page)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Global Settings"))
        self.chrome_version_label.setText(_translate("Dialog", "Chrome version"))
        self.checkBox_autoreg.setText(_translate("Dialog", "enable autoreg (betta)"))
        self.pushButton_remove_page.setText(_translate("Dialog", "-"))
        self.pushButton_add_page.setText(_translate("Dialog", "+"))
