# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI\settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(478, 451)
        Dialog.setStyleSheet("QPushButton{\n"
"height: 36px;\n"
"border: 1px solid;\n"
"border-radius: 4px;\n"
"border-color:  rgba(0, 0, 0, 0.12);\n"
"color: #6200ee;\n"
"font: \"Roboto\";\n"
"font-size: 20px;\n"
"padding: 5px\n"
"}\n"
"QPushButton::hover{\n"
"    background-color: rgb(230, 230, 230);\n"
"}\n"
"QPushButton::pressed{\n"
"    background-color: rgb(179, 179, 179);\n"
"}\n"
"\n"
"QListWidget{\n"
"border: none;\n"
"}\n"
"QLineEdit{\n"
"border: none;\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.user_agent_label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_agent_label.sizePolicy().hasHeightForWidth())
        self.user_agent_label.setSizePolicy(sizePolicy)
        self.user_agent_label.setObjectName("user_agent_label")
        self.verticalLayout_4.addWidget(self.user_agent_label)
        self.user_agent_line = QtWidgets.QLineEdit(Dialog)
        self.user_agent_line.setObjectName("user_agent_line")
        self.verticalLayout_4.addWidget(self.user_agent_line)
        self.label_line_number = QtWidgets.QLabel(Dialog)
        self.label_line_number.setObjectName("label_line_number")
        self.verticalLayout_4.addWidget(self.label_line_number)
        self.lineEdit_line_number = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_line_number.setObjectName("lineEdit_line_number")
        self.verticalLayout_4.addWidget(self.lineEdit_line_number)
        self.extensions_label = QtWidgets.QLabel(Dialog)
        self.extensions_label.setObjectName("extensions_label")
        self.verticalLayout_4.addWidget(self.extensions_label)
        self.listWidgetExtensions = QtWidgets.QListWidget(Dialog)
        self.listWidgetExtensions.setObjectName("listWidgetExtensions")
        self.verticalLayout_4.addWidget(self.listWidgetExtensions)
        self.passwords_label = QtWidgets.QLabel(Dialog)
        self.passwords_label.setObjectName("passwords_label")
        self.verticalLayout_4.addWidget(self.passwords_label)
        self.passwords_textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.passwords_textBrowser.setObjectName("passwords_textBrowser")
        self.verticalLayout_4.addWidget(self.passwords_textBrowser)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_3)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Settings"))
        self.user_agent_label.setText(_translate("Dialog", "User agent"))
        self.label_line_number.setText(_translate("Dialog", "Line number (only for autoreg)"))
        self.extensions_label.setText(_translate("Dialog", "Extensions"))
        self.passwords_label.setText(_translate("Dialog", "Passwords"))
